#
#  ----- Base docker image for transpilation -----
FROM node:12.16.1-alpine3.9 as builder
WORKDIR /usr/src
COPY package*.json tsconfig.json .mocharc.json .eslintrc.js ./
COPY /app ./app/
ENV NODE_ENV=development
# configure node
RUN npm set progress=false && npm config set depth 0 && \
    # install all dependencies
    npm install && \
    # compile code
    npx tsc

#
# ----- Test image -----
FROM builder as test
COPY . .

# install all dependencies
# RUN npm install

# RUN npm run test

RUN \
    # npm run coverage && \
    npm ci --production

#
# ----- Release image -----
FROM node:12.16.1-alpine3.9 as release

WORKDIR /app

# copy of transpiled app
COPY --from=builder /usr/src/dist/app ./dist/
# copy of production dependencies
COPY --from=test /usr/src/node_modules/ ./node_modules

# set default env variables
ENV PORT=3000
ENV NODE_ENV=production
ENV DEBUG=app:*

EXPOSE $PORT

ENTRYPOINT ["node"]

CMD ["./dist/server.js"]
