version: "3"

services:
  aiotes2fiware:
    image: aiotes/fiware-enabler
    environment:
      NODE_ENV: "prod"
      MONGO_URI: "mongodb://localhost:27017"
      HTTP_PORT: 3000
      API_KEY: ""
      API_CONTACT_NAME: ""
      API_CONTACT_URL: ""
      API_CONTACT_EMAIL: amartinez@mysphera.com
    ports:
      - "3000:3000"
